Add Dockerfile
ConservationMetrics/mbgl-tile-renderer pull request #8
Opened 2024-01-25 01:14 UTC by luandro

Adds Dockerfile, currently throwing same error and not running with docker:
```
Error: libicui18n.so.70: cannot open shared object file: No such file or directory
```

2024-01-25 02:33 UTC, rudokemper commented
As it stands, running a Docker image built with this Dockerfile produces this error, which seems to also be happening in arch architecture:

```
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libicui18n.so.70: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/@maplibre/maplibre-gl-native/platform/node/index.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.17.0
```

I tried to substitute the libicu66 downloads for libicu70, but that has a compatibility issue with the base image. So this will require some work. Maybe we need to pursue a multi-stage built where Maplibre native is built in an environment with the right ICU version, and then copied over to this image?

2024-01-25 02:34 UTC, rudokemper requested changes

2024-01-29 23:33 UTC, luandro commented
Still has error with display.

2024-01-30 13:40 UTC, rudokemper approved these changes
Awesome, thank you! Can we keep it scoped by removing the already merged changes related to tileSize in `src`?

Also, I inadvertently committed an output.mbtiles file in my PR to your branch. My bad, let's get rid of that. (And maybe add *.mbtiles to `.gitignore`, but I can do that too)

2024-01-30 20:54 UTC, merged